### ISSUE TITLE
Can't use this parser with flow types

### ISSUE THREAD

**Issue by igidas** [mysticatea/vue-eslint-parser#10]
Hey,

I use Flow types types inside javascript part of .vue files.
Then using this parser for '.vue' files I get unexpected token errors from Flow. Then switching back, to use 'babel-eslint' and 'eslint-plugin-html' to parse .vue files, Flow error dismiss.

I don't know if this is a right place for an issue, but it looks like 'vue-eslint-parses' somehow makes Flow to check also html part of the file instead of only the script.

Flow type checking is done by 'eslint-plugin-flowtype' and 'eslint-plugin-flowtype-errors' packages.
Error looks like:
`  11:11  error  Unexpected token !:       flowtype-errors/show-errors  `
In .vue file this line is Html comment.

**Comment by mysticatea** [comment]
Thank you for this issue.

It looks confliction that `vue-eslint-parser` cannot solve.

- The `eslint-plugin-flowtype` and `eslint-plugin-flowtype-errors` seem to require only inside of `<script>`, so it has to strip the code by preprocessors.
- The `eslint-plugin-vue` requires outside of `<script>` to verify templates, so does not work if it strips the code by preprocessors.

You have to separate those. For example:

    $ eslint "src/**/*.vue" -c vue.eslintrc.js && eslint "src/**/*.vue" -c flow.eslintrc.js

**Comment by mysticatea** [comment]
I got an idea.

It needs the supports of `eslint-plugin-flowtype` and `eslint-plugin-flowtype-errors`.

The `Program` node (the root of AST) has the range of the source code of the program. In general, this is whole the source code. However, the JS code of `.vue` files are inside of the top-level `<script>` element, so the range of the `Program` node is the inside of the top-level `<script>` element.

If `eslint-plugin-flowtype` and `eslint-plugin-flowtype-errors` plugins use only the source code of `Program` node, we can get good collaboration with `eslint-plugin-flowtype` and `eslint-plugin-flowtype-errors`, and `eslint-plugin-vue`.

**Comment by igidas** [comment]
Thanks for an quick answer. Should I create issue about this in `eslint-plugin-flowtype` repo?

**Comment by mysticatea** [comment]
Yes, please.

After re-look, `eslint-plugin-flowtype` is no problem since it's using AST. But `eslint-plugin-flowtype-errors` is [using source code text instead of AST](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/90a594c4de534e38b608586afa70d1256b6f9f67/src/index.js#L112), so it has this problem now.

Please open issue in `eslint-plugin-flowtype-errors`.

**Comment by mysticatea** [comment]
Closing this issue as favor of https://github.com/amilajack/eslint-plugin-flowtype-errors/issues/95.
