### ISSUE TITLE
2.0.0-beta.8 - inflinite loop while used with eslint-plugin-vue

### ISSUE THREAD

**Issue by armano2** [mysticatea/vue-eslint-parser#16]
https://gist.github.com/armano2/c34068d62fdb190a37e1a43ad0f88faf

**Comment by mysticatea** [comment]
Thank you for the report.

Mmmm, indeed, it has circular references between variables and references. `RuleTester` looks to clone AST deeply to check whether the rule does not modify the AST. The circular references interfere the cloning.

I will investigate solution.

**Comment by mysticatea** [comment]
I fixed it in https://github.com/mysticatea/vue-eslint-parser/commit/396eef6316238ecfc14135c16dc87217e992765a as configure some properties as non-enumerable.
