### ISSUE TITLE
npm warning for dependency on eslint@>=3.9.0 but I have 4.17.0 installed

### ISSUE THREAD

**Issue by pdagosto** [mysticatea/vue-eslint-parser#24]
myuserid@localhost ~]$ sudo npm install -g vue-eslint-parser
/usr/lib
├── UNMET PEER DEPENDENCY eslint@>=3.9.0
└─┬ vue-eslint-parser@2.0.2 
  ├─┬ debug@3.1.0 
  │ └── ms@2.0.0 
  ├─┬ eslint-scope@3.7.1 
  │ ├─┬ esrecurse@4.2.0 
  │ │ └── object-assign@4.1.1 
  │ └── estraverse@4.2.0 
  ├── eslint-visitor-keys@1.0.0 
  ├─┬ espree@3.5.3 
  │ ├── acorn@5.4.1 
  │ └─┬ acorn-jsx@3.0.1 
  │   └── acorn@3.3.0 
  ├── esquery@1.0.0 
  └── lodash@4.17.5 

npm WARN vue-eslint-parser@2.0.2 requires a peer of eslint@>=3.9.0 but none was installed.
myuserid@localhost ~]$ eslint --version
v4.17.0

**Comment by mysticatea** [comment]
Thank you for this issue.

It's npm matter.
npm handles the global registry and project-local registries as isolated. Your `eslint` command is in the global (`npm install -g eslint`), but `vue-eslint-parser` is in a project-local (without `-g` flag). So the `UNMET PEER DEPENDENCY` warning is right.

**Comment by mysticatea** [comment]
A side note: We (ESLint core team) recommend that people don't install `eslint` to global.

**Comment by pdagosto** [comment]
You're making an incorrect assumption. Both eslint and vue-eslint-parser were installed globally, as you can clearly see in the command line in my original post. So the warning is incorrect. 

I'm aware of the recommendation regarding global vs project local installations but it makes no sense to me so I don't follow it. I'm using these tools through emacs which has to find them in my path. I'm not interested in having to add each project directory to my path or having a different editor configuration for each project . This is how I have worked with every other emacs plugin for many years and I see no reason to change.

**Comment by mysticatea** [comment]
I got it.
However, in that case, it's npm's matter. I recommend opening an issue on https://github.com/npm/npm.
