### ISSUE TITLE
parserOptions has not passed to <script> parser

### ISSUE THREAD

**Issue by jzz4012650** [mysticatea/vue-eslint-parser#33]
## Version 
v4.0.2

## Steps to reproduce
add config below in `.eslintrc.js`:
```js
{
  parse: 'vue-eslint-parser',
  parserOptions: {
    parser: 'babel-eslint',
    legacyDecorators: true
  },
}
```

and then run `./node_modules/.bin/eslint ./src`, but got this error:

![image](https://user-images.githubusercontent.com/4429264/49426091-70129f80-f7da-11e8-8f1c-13dfcd239e60.png)

## What is expected?
config: `legacyDecorators: true` should works. 

## What is actually happening?
config: `legacyDecorators: true` has not passed to `babel-eslint`.

if I just use `babel-eslint` and set `legacyDecorators: true` in `parserOptions`, every thing works fine.

**Comment by mysticatea** [comment]
Thank you for this issue.

But it's not a problem in this parser. The `babel-eslint` doesn't have `legacyDecorators` option. Probably you want `ecmaFeatures.legacyDecorators` option: https://github.com/babel/babel-eslint/blob/3f61a68a049293715e4a6bd2549c7fd21c8c14dc/lib/parse.js#L10

**Comment by jzz4012650** [comment]
Sorry, My fault...

When I realized that, you have already replied my issue, great speed! XD
