### ISSUE TITLE
Check compatibility with ESLint 6

### ISSUE THREAD

**Issue by IlCallo** [mysticatea/vue-eslint-parser#54]
Most of the tooling around Vue shifted to ESLint 6 in past few weeks, can you check if everything works fine using it and bump dependencies?
Seems like a PR is already there, ready for review https://github.com/mysticatea/vue-eslint-parser/pull/51

**Comment by ba55ie** [comment]
Yes please! Currently we can't use `ecmaVersion: 2020` with [support for dynamic imports](https://eslint.org/blog/2019/08/eslint-v6.2.0-released). This will give the error ` Parsing error: Invalid ecmaVersion`, because the `espree` version is too old.

**Comment by juhasev** [comment]
Hopefully this gets out soon!

**Comment by skyrpex** [comment]
I've been using it with version 6 and found to issues to this day.

**Comment by pmochine** [comment]
+

**Comment by fengerzh** [comment]
As eslint-plugin-vue 6.0.0 released, this is the only blocking issue for upgrading to ESlint 6. Please help to solve it. Thanks!

**Comment by mysticatea** [comment]
Sorry for the lack of my activity. I have released v6.0.5 that fixed this problem.
