### ISSUE TITLE
Parsing is incompatible with typescript-eslint v2

### ISSUE THREAD

**Issue by IlCallo** [mysticatea/vue-eslint-parser#55]
As noted [here](https://github.com/vuejs/eslint-plugin-vue/issues/944), there is some kind of problems with applying Vue ESLint rules on SFC together with `typescript-eslint` v2.
Can you take a look at this and provide some insight on how the problem can be solved?

In my case, I get a `Parsing error: '>' expected` in every single Vue SFC, plus multiple template related errors.
I'm using Quasar, with `app-extension-typescript`, just to give some context.

![image](https://user-images.githubusercontent.com/10036108/63256359-b11ee700-c277-11e9-973c-2d00e35db935.png)

This seems related to the fact that the code actually read and linted is a transformation of the original one.
For example, `v-on` are listeners on `click` events (`@click.left="$emit('something')"`) and the parser is probably complaining about the `click` word being used into JS.

**Comment by GodofHope** [comment]
So how could I solve it?

**Comment by amritk** [comment]
I am stuck on this as well, have tried many things but can't seem to figure this one out.

**Comment by amritk** [comment]
Looks like this was fixed

**Comment by IlCallo** [comment]
I'll close the issue as soon as I have time to check if it solves problems I had on that project :)

**Comment by IlCallo** [comment]
I confirm issues are finally gone :)
