### ISSUE TITLE
Yarn v2 (pnp) compatibility with custom parser

### ISSUE THREAD

**Issue by AlexandreBonaventure** [mysticatea/vue-eslint-parser#64]
Hello, 
when using vue-eslint-parser + custom parser (with typescript here) in the context of yarn v2 we get the following error:
```
Parsing error: A package is trying to access another package without the second one being listed as a dependency of the first one

Required package: @typescript-eslint/parser (via "@typescript-eslint/parser")
Required by: vue-eslint-parser
```
This comes from:
https://github.com/mysticatea/vue-eslint-parser/blob/ea156df3872da715d580ea1c9c67a2c6e340b9ee/src/script/index.ts#L570

Yarn v2 is now enforcing require to be strict (no extraneous deps). In this case, I think the solution could be to make the `parserOptions.parser` to be the parser itself instead of a string. This way we can actually outsource the require call in the userland (here eslint-config-typescript: https://github.com/vuejs/eslint-config-typescript/blob/master/index.js#L8). It is up to the consuming library then to define its own dependencies.
This is an open discussion, I'm no expert here, but I'll be willing to PR if we agree on a solution.

ref: https://github.com/vuejs/vue-cli/issues/5135

**Comment by armano2** [comment]
this field is custom because there are many more parsers than just typescript,

espree, typescript, jest, coffeescript or any parser that is custom for set company, eg with nearley

**Comment by AlexandreBonaventure** [comment]
yes, I get that, what I mean is: there is probably a solution of passing this custom parser in such way that it is compatible with yarn by supporting to directly forward the parser and not just a string

**Comment by mysticatea** [comment]
That `parserOptions.parser` field is compatible with the top-level `parser` field, so it's a string. I guess that you can use `require.resolve("@typescript-eslint/parser")` to give an absolute path for the parser.

**Comment by AlexandreBonaventure** [comment]
ok thanks, this works fine 👍 I've updated this PR https://github.com/vuejs/eslint-config-typescript/pull/8

Closing that one
