### ISSUE TITLE
VOnExpression location error

### ISSUE THREAD

**Issue by AmmyXu** [mysticatea/vue-eslint-parser#81]
Hi!

Recently I've been using the vue-eslint-parser to analyze the vue file. I found that when VExpressionContainer. expression is VOnExpression , the range of expression mybe error.

For example:
codesandbox url： https://codesandbox.io/s/agitated-bush-hdvn0?file=/src/index.js

For the file code1.vue, the range of `test('something')`  is  [28,45]. This is correct.
But  for the file code2.vue,  the range of `test('something')`  is [29,46]. There is an 1 offset error.

![image](https://user-images.githubusercontent.com/29430746/90896559-730e5300-e3f6-11ea-8205-036f0014f7fb.png)

I hope you can fix the problem. Thank you very much

**Comment by triforcely** [comment]
@AmmyXu This PR should fix that https://github.com/mysticatea/vue-eslint-parser/pull/74 but this projects seems to be abandoned :(

**Comment by AmmyXu** [comment]
Thank you for your reply. 
Do you plan to solve this problem in the next version ? When will it be settled？

**Comment by ota-meshi** [comment]
It's a duplicate issue, so I close this issue. You can follow #74 and #50 to find out their status.
